# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 549d6f3ac93a7ef3a2d50d423f1ea83f4aaf6556e4cb9e38aa3c18c84b4ff443d8dd137431e2c7bf8e70e9e9c00153020f2e1cb781a1a7eee5ec9e3fbf5cdab1

test:
  secret_key_base: 2c5691d79ebdf2afe7461c62d5b321b2e144c794aea9c6fb46f51657383eed07ee1a207c7255541b74e2b4234a8929183e7e1b4857de0c297b8c7c72428c9921

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
